Add task to migrate from s3 to local storage
CodiTramuntana/decidim-module-cdtb pull request #1
Opened 2023-04-26 21:17 UTC by tramuntanal

2023-04-27 07:18 UTC, laurajaime requested changes
Good job!! 

Only some details.

2023-04-27 07:18 UTC, laurajaime commented on CHANGELOG.md
> +## [0.1.1] - 2023-04-27 (Una mascota trapellota)
😂

2023-04-27 07:18 UTC, laurajaime commented on README.md
> +2. Move the downloaded assets into the local storage directory doing the sarding:
```suggestion
2. Move the downloaded assets into the local storage directory doing the sharding:
```

2023-04-27 07:18 UTC, laurajaime commented on README.md
> +
Can you remove the extra spaces, please? 😅

2023-04-27 07:18 UTC, laurajaime commented on lib/decidim/cdtb/task.rb
> +      # May be used by sublasses for preparing before executing the task
```suggestion
      # May be used by subclasses for preparing before executing the task
```

2023-04-27 07:18 UTC, laurajaime commented on lib/decidim/cdtb/task.rb
> +      # May be used by sublasses for doing whatever after executing the task
```suggestion
      # May be used by subclasses for doing whatever after executing the task
```

2023-04-28 16:30 UTC, tramuntanal commented
Thanks for the review, corrections applied! :eyes:

2023-05-02 05:17 UTC, merged